import { prisma } from "./lib/prisma";


async function main() {
  await prisma.preorder.deleteMany();

  await prisma.preorder.createMany({
    data: [
      {
        name: "iPhone 15 Pro Max Preorder",
        products: 320,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-01"),
        endsAt: null,
        status: true,
      },
      {
        name: "MacBook Air M3 Launch Batch",
        products: 85,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-02"),
        endsAt: new Date("2026-06-12"),
        status: false,
      },
      {
        name: "Samsung Galaxy S24 Ultra Drop",
        products: 410,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-03"),
        endsAt: null,
        status: true,
      },
      {
        name: "Sony WH-1000XM6 Headphones",
        products: 140,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-04"),
        endsAt: new Date("2026-06-18"),
        status: true,
      },
      {
        name: "Nintendo Switch OLED Special",
        products: 230,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-05"),
        endsAt: null,
        status: false,
      },
      {
        name: "Apple Watch Series 10 Edition",
        products: 190,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-06"),
        endsAt: new Date("2026-06-22"),
        status: true,
      },
      {
        name: "Dell XPS 15 Premium Batch",
        products: 60,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-07"),
        endsAt: null,
        status: true,
      },
      {
        name: "PlayStation 6 Early Access",
        products: 520,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-08"),
        endsAt: null,
        status: false,
      },
      {
        name: "AirPods Pro 3 Launch Drop",
        products: 275,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-09"),
        endsAt: new Date("2026-06-25"),
        status: true,
      },
      {
        name: "Google Pixel 9 Pro Preorder",
        products: 95,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-10"),
        endsAt: null,
        status: true,
      },

      {
        name: "Xiaomi 14 Ultra Batch",
        products: 300,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-11"),
        endsAt: null,
        status: true,
      },
      {
        name: "Asus ROG Phone 8 Gaming",
        products: 180,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-12"),
        endsAt: new Date("2026-06-30"),
        status: false,
      },
      {
        name: "HP Spectre x360 Premium",
        products: 75,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-13"),
        endsAt: null,
        status: true,
      },
      {
        name: "Lenovo Legion 9 Gaming Beast",
        products: 220,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-14"),
        endsAt: new Date("2026-06-28"),
        status: true,
      },
      {
        name: "Bose QuietComfort Ultra Headset",
        products: 160,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-15"),
        endsAt: null,
        status: false,
      },
      {
        name: "OnePlus 12 Global Drop",
        products: 340,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-16"),
        endsAt: null,
        status: true,
      },
      {
        name: "Nothing Phone 3 Launch",
        products: 210,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-17"),
        endsAt: new Date("2026-07-01"),
        status: true,
      },
      {
        name: "iPad Pro M4 Batch",
        products: 260,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-18"),
        endsAt: null,
        status: false,
      },
      {
        name: "Samsung Tab S10 Ultra",
        products: 150,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-19"),
        endsAt: new Date("2026-07-05"),
        status: true,
      },
      {
        name: "GoPro Hero 13 Launch",
        products: 90,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-20"),
        endsAt: null,
        status: true,
      },

      {
        name: "DJI Mini 5 Drone Batch",
        products: 130,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-21"),
        endsAt: new Date("2026-07-10"),
        status: true,
      },
      {
        name: "Canon EOS R8 Camera Drop",
        products: 70,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-22"),
        endsAt: null,
        status: false,
      },
      {
        name: "Sony Alpha A7 IV Pro Batch",
        products: 110,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-23"),
        endsAt: new Date("2026-07-12"),
        status: true,
      },
      {
        name: "Fujifilm X100VI Edition",
        products: 95,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-24"),
        endsAt: null,
        status: true,
      },
      {
        name: "Razer Blade 16 Gaming Laptop",
        products: 140,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-25"),
        endsAt: null,
        status: true,
      },
      {
        name: "MSI Titan GT77 Ultra",
        products: 65,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-26"),
        endsAt: new Date("2026-07-20"),
        status: false,
      },
      {
        name: "Steam Deck OLED Refresh",
        products: 380,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-27"),
        endsAt: null,
        status: true,
      },
      {
        name: "Meta Quest 4 VR Headset",
        products: 290,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-28"),
        endsAt: new Date("2026-07-25"),
        status: true,
      },
      {
        name: "Logitech MX Master 4 Mouse",
        products: 500,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-06-29"),
        endsAt: null,
        status: false,
      },
      {
        name: "Anker PowerBank Ultra 25000mAh",
        products: 600,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-06-30"),
        endsAt: null,
        status: true,
      },

      {
        name: "JBL Tour Pro 3 Earbuds",
        products: 240,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-07-01"),
        endsAt: new Date("2026-07-15"),
        status: true,
      },
      {
        name: "Realme GT 6 Turbo Edition",
        products: 330,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-07-02"),
        endsAt: null,
        status: true,
      },
      {
        name: "Vivo X100 Pro Max Drop",
        products: 270,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-07-03"),
        endsAt: new Date("2026-07-18"),
        status: false,
      },
      {
        name: "Oppo Find X7 Ultra Batch",
        products: 210,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-07-04"),
        endsAt: null,
        status: true,
      },
      {
        name: "Huawei Mate 60 Pro Plus",
        products: 190,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-07-05"),
        endsAt: new Date("2026-07-22"),
        status: true,
      },
      {
        name: "Tesla Phone Prototype Drop",
        products: 999,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-07-06"),
        endsAt: null,
        status: false,
      },
      {
        name: "Alienware Aurora R16 Beast",
        products: 120,
        preorderWhen: "OUT_OF_STOCK",
        startsAt: new Date("2026-07-07"),
        endsAt: new Date("2026-07-30"),
        status: true,
      },
      {
        name: "Surface Laptop Studio 3",
        products: 160,
        preorderWhen: "REGARDLESS_OF_STOCK",
        startsAt: new Date("2026-07-08"),
        endsAt: null,
        status: true,
      },
    ],
  });

  console.log("Seed completed successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
